### ISSUE TITLE
Problem: edge case of indexer causes it won't work

### ISSUE THREAD

**Issue by VictorTrustyDev** [crypto-org-chain/ethermint#397]
Currently, indexer if not able to fetch a block result, it will retry infinity so on a prune-node, there is an edge case that indexer is turned-off at the past, the data on db is exists, LastIndexedBlock returns positive number but that block is already pruned and the indexer can not back to work.

@yihuang can you confirm?

If that is correct, shall we force the `lastBlock` variable to node's earliest/latest height?
The missing gap is not important because the indexer in any node prune will be missing txs the same as it is.

```golang
if lastBlock == -1 {
	lastBlock = latestBlock
} else if lastBlock < status.SyncInfo.EarliestBlockHeight {
	lastBlock = status.SyncInfo.EarliestBlockHeight // or latestBlock
	// kinda unsafe, but we don't have a better way to do this
}
```

**Comment by yihuang** [comment]
> @yihuang can you confirm?

Yeah, I think the analysis of the issue is correct.
